# =========================================================================
# Makefile puente (Ubicado en la carpeta /img)
# =========================================================================

# Esta regla atrapa cualquier comando y lo ejecuta en la carpeta superior (..)
%:
	$(MAKE) -C .. $@