/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

/* hdlname = "multiplicador" */
/* top =  1  */
/* src = "multiplicador.v:1.1-60.10" */
module multiplicador(reset, clk, start, A, B, p, done);
  /* src = "multiplicador.v:5.18-5.19" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "multiplicador.v:6.18-6.19" */
  input [15:0] B;
  wire [15:0] B;
  /* hdlname = "accum0 A" */
  /* src = "accum.v:3.18-3.19" */
  wire [31:0] \accum0.A ;
  /* hdlname = "accum0 add" */
  /* src = "accum.v:4.11-4.14" */
  wire \accum0.add ;
  wire \accum0.add_TRELLIS_FF_Q_DI ;
  /* hdlname = "accum0 clk" */
  /* src = "accum.v:2.11-2.14" */
  wire \accum0.clk ;
  /* hdlname = "accum0 p" */
  /* src = "accum.v:6.23-6.24" */
  wire [31:0] \accum0.p ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_10_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_11_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_12_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_13_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_14_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_15_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  /* unused_bits = "0" */
  wire \accum0.p_CCU2C_A0_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_7_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_8_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_9_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \accum0.p_CCU2C_A0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [31:0] \accum0.p_TRELLIS_FF_Q_DI ;
  /* hdlname = "accum0 reset" */
  /* src = "accum.v:5.11-5.16" */
  wire \accum0.reset ;
  /* src = "multiplicador.v:3.11-3.14" */
  input clk;
  wire clk;
  /* hdlname = "comparador0 B" */
  /* src = "comparador.v:2.18-2.19" */
  wire [15:0] \comparador0.B ;
  /* hdlname = "control0 add" */
  /* src = "control.v:11.16-11.19" */
  wire \control0.add ;
  /* hdlname = "control0 clk" */
  /* src = "control.v:2.16-2.19" */
  wire \control0.clk ;
  /* hdlname = "control0 count" */
  /* src = "control.v:22.11-22.16" */
  wire [4:0] \control0.count ;
  wire \control0.count_TRELLIS_FF_Q_CE ;
  wire [4:0] \control0.count_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 done" */
  /* src = "control.v:8.16-8.20" */
  wire \control0.done ;
  /* hdlname = "control0 lsb_B" */
  /* src = "control.v:4.16-4.21" */
  wire \control0.lsb_B ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control0.lsb_B_LUT4_D_Z ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_C0 ;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0 ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1 ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_ALUT ;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_C0 ;
  wire [14:0] \control0.lsb_B_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 reset_out" */
  /* src = "control.v:10.16-10.25" */
  wire \control0.reset_out ;
  /* hdlname = "control0 rst" */
  /* src = "control.v:3.16-3.19" */
  wire \control0.rst ;
  /* hdlname = "control0 shft" */
  /* src = "control.v:9.16-9.20" */
  wire \control0.shft ;
  wire \control0.shft_LUT4_D_Z ;
  /* hdlname = "control0 start" */
  /* src = "control.v:5.16-5.21" */
  wire \control0.start ;
  /* onehot = 32'd1 */
  wire [4:0] \control0.state ;
  /* src = "multiplicador.v:8.12-8.16" */
  output done;
  wire done;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] done_LUT4_C_1_D;
  /* abc9_carry = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  /* unused_bits = "0" */
  wire done_LUT4_C_1_D_CCU2C_S0_COUT;
  /* unused_bits = "0" */
  wire done_LUT4_C_1_D_CCU2C_S0_S1;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] done_LUT4_C_2_D;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] done_LUT4_C_3_D;
  /* abc9_carry = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire done_LUT4_C_3_D_CCU2C_S0_COUT;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] done_LUT4_C_4_D;
  /* abc9_carry = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire done_LUT4_C_4_D_CCU2C_S1_COUT;
  /* unused_bits = "0" */
  wire done_LUT4_C_4_D_CCU2C_S1_S0;
  /* hdlname = "left_shift0 A_in" */
  /* src = "left_shift.v:3.18-3.22" */
  wire [31:0] \left_shift0.A_in ;
  /* hdlname = "left_shift0 clk" */
  /* src = "left_shift.v:2.11-2.14" */
  wire \left_shift0.clk ;
  /* hdlname = "left_shift0 load" */
  /* src = "left_shift.v:4.11-4.15" */
  wire \left_shift0.load ;
  /* hdlname = "left_shift0 s_A" */
  /* src = "left_shift.v:6.23-6.26" */
  wire [31:0] \left_shift0.s_A ;
  wire [15:1] \left_shift0.s_A_TRELLIS_FF_Q_30_DI ;
  wire \left_shift0.s_A_TRELLIS_FF_Q_31_LSR ;
  /* hdlname = "left_shift0 shift" */
  /* src = "left_shift.v:5.11-5.16" */
  wire \left_shift0.shift ;
  /* src = "multiplicador.v:7.19-7.20" */
  output [31:0] p;
  wire [31:0] p;
  /* src = "multiplicador.v:2.11-2.16" */
  input reset;
  wire reset;
  /* hdlname = "right_shift0 B_in" */
  /* src = "right_shift.v:3.18-3.22" */
  wire [15:0] \right_shift0.B_in ;
  /* hdlname = "right_shift0 clk" */
  /* src = "right_shift.v:2.11-2.14" */
  wire \right_shift0.clk ;
  /* hdlname = "right_shift0 load" */
  /* src = "right_shift.v:4.11-4.15" */
  wire \right_shift0.load ;
  /* hdlname = "right_shift0 shift" */
  /* src = "right_shift.v:5.11-5.16" */
  wire \right_shift0.shift ;
  /* hdlname = "right_shift0 shift_B" */
  /* src = "right_shift.v:6.23-6.30" */
  wire [15:0] \right_shift0.shift_B ;
  /* src = "multiplicador.v:4.11-4.16" */
  input start;
  wire start;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [3:0] start_LUT4_A_D;
  wire [4:0] start_LUT4_A_Z;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire start_LUT4_A_Z_PFUMX_Z_1_ALUT;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire start_LUT4_A_Z_PFUMX_Z_1_BLUT;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire start_LUT4_A_Z_PFUMX_Z_ALUT;
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire start_LUT4_A_Z_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] start_LUT4_C_Z;
  /* src = "multiplicador.v:16.13-16.16" */
  wire [31:0] w_A;
  /* src = "multiplicador.v:17.13-17.16" */
  wire [15:0] w_B;
  /* src = "multiplicador.v:13.6-13.11" */
  wire w_add;
  /* src = "multiplicador.v:12.6-12.13" */
  wire w_reset;
  /* src = "multiplicador.v:11.6-11.10" */
  wire w_sh;
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[10]),
    .C(\left_shift0.s_A [9]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[9]),
    .C(\left_shift0.s_A [8]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_10 (
    .A(1'h0),
    .B(A[14]),
    .C(\left_shift0.s_A [13]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_11 (
    .A(1'h0),
    .B(A[13]),
    .C(\left_shift0.s_A [12]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_12 (
    .A(1'h0),
    .B(A[12]),
    .C(\left_shift0.s_A [11]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_13 (
    .A(1'h0),
    .B(A[11]),
    .C(\left_shift0.s_A [10]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) A_LUT4_B_14 (
    .A(1'h0),
    .B(A[1]),
    .C(\accum0.reset ),
    .D(\left_shift0.s_A [0]),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[8]),
    .C(\left_shift0.s_A [7]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[7]),
    .C(\left_shift0.s_A [6]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[6]),
    .C(\left_shift0.s_A [5]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[5]),
    .C(\left_shift0.s_A [4]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[4]),
    .C(\left_shift0.s_A [3]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[3]),
    .C(\left_shift0.s_A [2]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_8 (
    .A(1'h0),
    .B(A[2]),
    .C(\left_shift0.s_A [1]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_9 (
    .A(1'h0),
    .B(A[15]),
    .C(\left_shift0.s_A [14]),
    .D(\accum0.reset ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B (
    .A(1'h0),
    .B(B[9]),
    .C(\right_shift0.shift_B [10]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_1 (
    .A(1'h0),
    .B(B[8]),
    .C(\right_shift0.shift_B [9]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_10 (
    .A(1'h0),
    .B(B[13]),
    .C(\right_shift0.shift_B [14]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_11 (
    .A(1'h0),
    .B(B[12]),
    .C(\right_shift0.shift_B [13]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_12 (
    .A(1'h0),
    .B(B[11]),
    .C(\right_shift0.shift_B [12]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_13 (
    .A(1'h0),
    .B(B[10]),
    .C(\right_shift0.shift_B [11]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_14 (
    .A(1'h0),
    .B(B[0]),
    .C(\right_shift0.shift_B [1]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_2 (
    .A(1'h0),
    .B(B[7]),
    .C(\right_shift0.shift_B [8]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_3 (
    .A(1'h0),
    .B(B[6]),
    .C(\right_shift0.shift_B [7]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_4 (
    .A(1'h0),
    .B(B[5]),
    .C(\right_shift0.shift_B [6]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_5 (
    .A(1'h0),
    .B(B[4]),
    .C(\right_shift0.shift_B [5]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_6 (
    .A(1'h0),
    .B(B[3]),
    .C(\right_shift0.shift_B [4]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_7 (
    .A(1'h0),
    .B(B[2]),
    .C(\right_shift0.shift_B [3]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_8 (
    .A(1'h0),
    .B(B[1]),
    .C(\right_shift0.shift_B [2]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_9 (
    .A(1'h0),
    .B(B[14]),
    .C(\right_shift0.shift_B [15]),
    .D(\accum0.reset ),
    .Z(\control0.lsb_B_TRELLIS_FF_Q_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \accum0.add_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\accum0.add_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\accum0.add )
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0  (
    .A0(\accum0.p [8]),
    .A1(\accum0.p [9]),
    .B0(\left_shift0.s_A [8]),
    .B1(\left_shift0.s_A [9]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_1_COUT ),
    .COUT(\accum0.p_CCU2C_A0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [8]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_1  (
    .A0(\accum0.p [6]),
    .A1(\accum0.p [7]),
    .B0(\left_shift0.s_A [6]),
    .B1(\left_shift0.s_A [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_2_COUT ),
    .COUT(\accum0.p_CCU2C_A0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [6]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_10  (
    .A0(\accum0.p [18]),
    .A1(\accum0.p [19]),
    .B0(\left_shift0.s_A [18]),
    .B1(\left_shift0.s_A [19]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_11_COUT ),
    .COUT(\accum0.p_CCU2C_A0_10_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [18]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_11  (
    .A0(\accum0.p [16]),
    .A1(\accum0.p [17]),
    .B0(\left_shift0.s_A [16]),
    .B1(\left_shift0.s_A [17]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_12_COUT ),
    .COUT(\accum0.p_CCU2C_A0_11_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [16]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_12  (
    .A0(\accum0.p [14]),
    .A1(\accum0.p [15]),
    .B0(\left_shift0.s_A [14]),
    .B1(\left_shift0.s_A [15]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_13_COUT ),
    .COUT(\accum0.p_CCU2C_A0_12_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [14]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_13  (
    .A0(\accum0.p [12]),
    .A1(\accum0.p [13]),
    .B0(\left_shift0.s_A [12]),
    .B1(\left_shift0.s_A [13]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_14_COUT ),
    .COUT(\accum0.p_CCU2C_A0_13_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [12]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_14  (
    .A0(\accum0.p [10]),
    .A1(\accum0.p [11]),
    .B0(\left_shift0.s_A [10]),
    .B1(\left_shift0.s_A [11]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_COUT ),
    .COUT(\accum0.p_CCU2C_A0_14_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [10]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_15  (
    .A0(\accum0.p [0]),
    .A1(\accum0.p [1]),
    .B0(\left_shift0.s_A [0]),
    .B1(\left_shift0.s_A [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\accum0.p_CCU2C_A0_15_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [0]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_2  (
    .A0(\accum0.p [4]),
    .A1(\accum0.p [5]),
    .B0(\left_shift0.s_A [4]),
    .B1(\left_shift0.s_A [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_4_COUT ),
    .COUT(\accum0.p_CCU2C_A0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [4]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_3  (
    .A0(\accum0.p [30]),
    .A1(\accum0.p [31]),
    .B0(\left_shift0.s_A [30]),
    .B1(\left_shift0.s_A [31]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_5_COUT ),
    .COUT(\accum0.p_CCU2C_A0_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [30]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_4  (
    .A0(\accum0.p [2]),
    .A1(\accum0.p [3]),
    .B0(\left_shift0.s_A [2]),
    .B1(\left_shift0.s_A [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_15_COUT ),
    .COUT(\accum0.p_CCU2C_A0_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [2]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_5  (
    .A0(\accum0.p [28]),
    .A1(\accum0.p [29]),
    .B0(\left_shift0.s_A [28]),
    .B1(\left_shift0.s_A [29]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_6_COUT ),
    .COUT(\accum0.p_CCU2C_A0_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [28]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_6  (
    .A0(\accum0.p [26]),
    .A1(\accum0.p [27]),
    .B0(\left_shift0.s_A [26]),
    .B1(\left_shift0.s_A [27]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_7_COUT ),
    .COUT(\accum0.p_CCU2C_A0_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [26]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_7  (
    .A0(\accum0.p [24]),
    .A1(\accum0.p [25]),
    .B0(\left_shift0.s_A [24]),
    .B1(\left_shift0.s_A [25]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_8_COUT ),
    .COUT(\accum0.p_CCU2C_A0_7_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [24]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_8  (
    .A0(\accum0.p [22]),
    .A1(\accum0.p [23]),
    .B0(\left_shift0.s_A [22]),
    .B1(\left_shift0.s_A [23]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_9_COUT ),
    .COUT(\accum0.p_CCU2C_A0_8_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [22]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:13.24-13.27|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \accum0.p_CCU2C_A0_9  (
    .A0(\accum0.p [20]),
    .A1(\accum0.p [21]),
    .B0(\left_shift0.s_A [20]),
    .B1(\left_shift0.s_A [21]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\accum0.p_CCU2C_A0_10_COUT ),
    .COUT(\accum0.p_CCU2C_A0_9_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\accum0.p_TRELLIS_FF_Q_DI [20]),
    .S1(\accum0.p_TRELLIS_FF_Q_DI [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [31]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_1  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [30]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_10  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [21]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_11  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [20]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_12  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [19]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_13  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [18]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_14  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [17]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_15  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [16]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_16  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [15]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_17  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [14]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_18  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [13]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_19  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [12]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_2  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [29]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_20  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [11]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_21  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [10]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_22  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [9]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_23  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [8]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_24  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [7]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_25  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [6]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_26  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [5]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_27  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [4]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_28  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [3]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_29  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [2]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_3  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [28]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_30  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [1]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_31  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [0]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_4  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [27]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_5  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [26]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_6  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [25]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_7  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [24]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_8  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [23]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "accum.v:8.1-15.12|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \accum0.p_TRELLIS_FF_Q_9  (
    .CE(\accum0.add ),
    .CLK(clk),
    .DI(\accum0.p_TRELLIS_FF_Q_DI [22]),
    .LSR(\accum0.reset ),
    .Q(\accum0.p [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \accum0.reset_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(start_LUT4_A_Z[0]),
    .LSR(1'h0),
    .Q(\accum0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:24.1-69.4|/usr/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q  (
    .CE(\control0.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [4]),
    .LSR(reset),
    .Q(\control0.count [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:24.1-69.4|/usr/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_1  (
    .CE(\control0.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [3]),
    .LSR(reset),
    .Q(\control0.count [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:24.1-69.4|/usr/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_2  (
    .CE(\control0.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [2]),
    .LSR(reset),
    .Q(\control0.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:24.1-69.4|/usr/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_3  (
    .CE(\control0.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [1]),
    .LSR(reset),
    .Q(\control0.count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:24.1-69.4|/usr/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_4  (
    .CE(\control0.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [0]),
    .LSR(reset),
    .Q(\control0.count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D  (
    .A(\right_shift0.shift_B [3]),
    .B(\right_shift0.shift_B [2]),
    .C(\right_shift0.shift_B [1]),
    .D(\control0.lsb_B ),
    .Z(\control0.lsb_B_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT  (
    .ALUT(\control0.lsb_B_LUT4_D_Z ),
    .BLUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_C0 [4]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_C0_LUT4_Z  (
    .A(\right_shift0.shift_B [15]),
    .B(\right_shift0.shift_B [14]),
    .C(\right_shift0.shift_B [13]),
    .D(\right_shift0.shift_B [12]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_C0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z  (
    .D0(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0 ),
    .D1(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1 ),
    .SD(\control0.count [0]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\control0.count [1]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h2aaa)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(done),
    .B(\control0.count [4]),
    .C(\control0.count [3]),
    .D(\control0.count [2]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(done),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\control0.count [1]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'h2aaa)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(done),
    .B(\control0.count [4]),
    .C(\control0.count [3]),
    .D(\control0.count [2]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'h2aaa)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(done),
    .B(\control0.count [4]),
    .C(\control0.count [3]),
    .D(\control0.count [2]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z  (
    .ALUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_C0 [4]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\right_shift0.shift_B [7]),
    .B(\right_shift0.shift_B [6]),
    .C(\right_shift0.shift_B [5]),
    .D(\right_shift0.shift_B [4]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_C0_LUT4_Z  (
    .A(\right_shift0.shift_B [11]),
    .B(\right_shift0.shift_B [10]),
    .C(\right_shift0.shift_B [9]),
    .D(\right_shift0.shift_B [8]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_C0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.lsb_B_TRELLIS_FF_Q  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [0]),
    .LSR(1'h0),
    .Q(\control0.lsb_B )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control0.shft_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\accum0.reset ),
    .D(\control0.shft ),
    .Z(\control0.shft_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.shft_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(start_LUT4_A_Z[4]),
    .LSR(1'h0),
    .Q(\control0.shft )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5054)
  ) \control0.state_LUT4_B  (
    .A(reset),
    .B(\control0.state [3]),
    .C(\accum0.add ),
    .D(\control0.lsb_B ),
    .Z(start_LUT4_A_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \control0.state_LUT4_C  (
    .A(1'h0),
    .B(reset),
    .C(\control0.state [3]),
    .D(\control0.lsb_B ),
    .Z(\accum0.add_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(start_LUT4_A_Z[3]),
    .LSR(1'h0),
    .Q(\control0.state [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) done_LUT4_C (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(\accum0.reset ),
    .Z(\control0.count_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) done_LUT4_C_1 (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(done_LUT4_C_1_D[1]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) done_LUT4_C_1_D_CCU2C_S0 (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.count [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(done_LUT4_C_3_D_CCU2C_S0_COUT),
    .COUT(done_LUT4_C_1_D_CCU2C_S0_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(done_LUT4_C_1_D[1]),
    .S1(done_LUT4_C_1_D_CCU2C_S0_S1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) done_LUT4_C_2 (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(done_LUT4_C_2_D[1]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) done_LUT4_C_3 (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(done_LUT4_C_3_D[1]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) done_LUT4_C_3_D_CCU2C_S0 (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.count [2]),
    .B1(\control0.count [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(done_LUT4_C_4_D_CCU2C_S1_COUT),
    .COUT(done_LUT4_C_3_D_CCU2C_S0_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(done_LUT4_C_3_D[1]),
    .S1(done_LUT4_C_2_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) done_LUT4_C_4 (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(done_LUT4_C_4_D[1]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control.v:57.26-57.38|/usr/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) done_LUT4_C_4_D_CCU2C_S1 (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.count [0]),
    .B1(\control0.count [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(done_LUT4_C_4_D_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(done_LUT4_C_4_D_CCU2C_S1_S0),
    .S1(done_LUT4_C_4_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_C_5 (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(\control0.count [0]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) done_TRELLIS_FF_Q (
    .CLK(clk),
    .DI(start_LUT4_A_Z[1]),
    .LSR(1'h0),
    .Q(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [30]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_1  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [29]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_10  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [20]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_11  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [19]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_12  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [18]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_13  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [17]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_14  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [16]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_15  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [15]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_16  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [15]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_17  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [14]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_18  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [13]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_19  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [12]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_2  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [28]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_20  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [11]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_21  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [10]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_22  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [9]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_23  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [8]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_24  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [7]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_25  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [6]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_26  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [5]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_27  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [4]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_28  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [3]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_29  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [2]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_3  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [27]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \left_shift0.s_A_TRELLIS_FF_Q_30  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\left_shift0.s_A_TRELLIS_FF_Q_30_DI [1]),
    .LSR(1'h0),
    .Q(\left_shift0.s_A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_31  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\left_shift0.s_A_TRELLIS_FF_Q_31_LSR ),
    .Q(\left_shift0.s_A [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \left_shift0.s_A_TRELLIS_FF_Q_31_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\accum0.reset ),
    .D(\control0.shft ),
    .Z(\left_shift0.s_A_TRELLIS_FF_Q_31_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_4  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [26]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_5  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [25]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_6  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [24]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_7  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [23]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_8  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [22]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "left_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \left_shift0.s_A_TRELLIS_FF_Q_9  (
    .CE(\control0.shft ),
    .CLK(clk),
    .DI(\left_shift0.s_A [21]),
    .LSR(\accum0.reset ),
    .Q(\left_shift0.s_A [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \right_shift0.shift_B_TRELLIS_FF_Q  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(B[15]),
    .LSR(\left_shift0.s_A_TRELLIS_FF_Q_31_LSR ),
    .Q(\right_shift0.shift_B [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_1  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [14]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_10  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [5]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_11  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [4]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_12  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [3]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_13  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [2]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_14  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [1]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_2  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [13]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_3  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [12]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_4  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [11]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_5  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [10]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_6  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [9]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_7  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [8]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_8  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [7]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "right_shift.v:9.1-15.4|/usr/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \right_shift0.shift_B_TRELLIS_FF_Q_9  (
    .CE(\control0.shft_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control0.lsb_B_TRELLIS_FF_Q_DI [6]),
    .LSR(1'h0),
    .Q(\right_shift0.shift_B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hffdc)
  ) start_LUT4_A (
    .A(start),
    .B(reset),
    .C(\accum0.reset ),
    .D(start_LUT4_A_D[3]),
    .Z(start_LUT4_A_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) start_LUT4_A_D_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [3]),
    .D(done),
    .Z(start_LUT4_A_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX start_LUT4_A_Z_PFUMX_Z (
    .ALUT(start_LUT4_A_Z_PFUMX_Z_ALUT),
    .BLUT(start_LUT4_A_Z_PFUMX_Z_BLUT),
    .C0(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [0]),
    .Z(start_LUT4_A_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX start_LUT4_A_Z_PFUMX_Z_1 (
    .ALUT(start_LUT4_A_Z_PFUMX_Z_1_ALUT),
    .BLUT(start_LUT4_A_Z_PFUMX_Z_1_BLUT),
    .C0(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [4]),
    .Z(start_LUT4_A_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h3320)
  ) start_LUT4_A_Z_PFUMX_Z_1_ALUT_LUT4_Z (
    .A(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [0]),
    .B(reset),
    .C(\control0.shft ),
    .D(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [3]),
    .Z(start_LUT4_A_Z_PFUMX_Z_1_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) start_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(reset),
    .D(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [3]),
    .Z(start_LUT4_A_Z_PFUMX_Z_1_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) start_LUT4_C (
    .A(1'h0),
    .B(1'h0),
    .C(start),
    .D(\accum0.reset ),
    .Z(start_LUT4_C_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h3310)
  ) start_LUT4_C_Z_LUT4_D (
    .A(\control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [4]),
    .B(reset),
    .C(\control0.shft ),
    .D(start_LUT4_C_Z[3]),
    .Z(start_LUT4_A_Z_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3330)
  ) start_LUT4_C_Z_LUT4_D_1 (
    .A(1'h0),
    .B(reset),
    .C(\control0.shft ),
    .D(start_LUT4_C_Z[3]),
    .Z(start_LUT4_A_Z_PFUMX_Z_BLUT)
  );
  assign done_LUT4_C_1_D[0] = done;
  assign start_LUT4_A_D[2:0] = { \accum0.reset , reset, start };
  assign \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [2:1] = { \control0.shft , reset };
  assign done_LUT4_C_2_D[0] = done;
  assign { start_LUT4_C_Z[4], start_LUT4_C_Z[2:0] } = { \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [0], \control0.shft , reset, \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z [4] };
  assign \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_Z_PFUMX_Z_C0 [3:0] = { \right_shift0.shift_B [4], \right_shift0.shift_B [5], \right_shift0.shift_B [6], \right_shift0.shift_B [7] };
  assign \control0.lsb_B_LUT4_D_Z_PFUMX_ALUT_C0 [3:0] = { \control0.lsb_B , \right_shift0.shift_B [1], \right_shift0.shift_B [2], \right_shift0.shift_B [3] };
  assign done_LUT4_C_3_D[0] = done;
  assign done_LUT4_C_4_D[0] = done;
  assign start_LUT4_A_Z[2] = \accum0.add_TRELLIS_FF_Q_DI ;
  assign \accum0.A  = \left_shift0.s_A ;
  assign \accum0.clk  = clk;
  assign \comparador0.B  = { \right_shift0.shift_B [15:1], \control0.lsb_B  };
  assign \control0.add  = \accum0.add ;
  assign \control0.clk  = clk;
  assign \control0.done  = done;
  assign \control0.reset_out  = \accum0.reset ;
  assign \control0.rst  = reset;
  assign \control0.start  = start;
  assign { \control0.state [4], \control0.state [2:0] } = { \control0.shft , \accum0.add , done, \accum0.reset  };
  assign \left_shift0.A_in  = { 16'h0000, A };
  assign \left_shift0.clk  = clk;
  assign \left_shift0.load  = \accum0.reset ;
  assign \left_shift0.shift  = \control0.shft ;
  assign p = \accum0.p ;
  assign \right_shift0.B_in  = B;
  assign \right_shift0.clk  = clk;
  assign \right_shift0.load  = \accum0.reset ;
  assign \right_shift0.shift  = \control0.shft ;
  assign \right_shift0.shift_B [0] = \control0.lsb_B ;
  assign w_A = \left_shift0.s_A ;
  assign w_B = { \right_shift0.shift_B [15:1], \control0.lsb_B  };
  assign w_add = \accum0.add ;
  assign w_reset = \accum0.reset ;
  assign w_sh = \control0.shft ;
endmodule
